// <auto-generated />
using System;
using DevForge.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevForge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevForge.Domain.Applications.App", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("branch");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("repository_url");

                    b.Property<string>("Runtime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("runtime");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_applications_created_at");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_applications_name");

                    b.ToTable("applications", (string)null);
                });

            modelBuilder.Entity("DevForge.Domain.Builds.Build", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("ArtifactReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("artifact_reference");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_builds");

                    b.HasIndex("ApplicationId", "StartedAt")
                        .HasDatabaseName("ix_builds_application_id_started_at");

                    b.ToTable("builds", null, t =>
                        {
                            t.HasCheckConstraint("ck_builds_status", "status IN ('Running', 'Succeeded', 'Failed')");
                        });
                });

            modelBuilder.Entity("DevForge.Domain.Deployments.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<Guid?>("BuildId")
                        .HasColumnType("uuid")
                        .HasColumnName("build_id");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentStage")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("current_stage");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<bool>("SimulateFailure")
                        .HasColumnType("boolean")
                        .HasColumnName("simulate_failure");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("worker_id");

                    b.HasKey("Id")
                        .HasName("pk_deployments");

                    b.HasIndex("BuildId")
                        .HasDatabaseName("ix_deployments_build_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_deployments_created_at");

                    b.HasIndex("ApplicationId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_deployments_application_id_number");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_deployments_status_created_at");

                    b.HasIndex(new[] { "ApplicationId" }, "ux_deployments_one_active_per_application")
                        .IsUnique()
                        .HasDatabaseName("ux_deployments_one_active_per_application")
                        .HasFilter("status IN ('Queued', 'Running')");

                    b.ToTable("deployments", null, t =>
                        {
                            t.HasCheckConstraint("ck_deployments_current_stage", "current_stage IN ('Preparing', 'Building', 'Testing', 'Deploying')");

                            t.HasCheckConstraint("ck_deployments_status", "status IN ('Queued', 'Running', 'Succeeded', 'Failed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("DevForge.Domain.Deployments.DeploymentLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("DeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("deployment_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("message");

                    b.Property<string>("Stage")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("stage");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id")
                        .HasName("pk_deployment_logs");

                    b.HasIndex("DeploymentId", "Id")
                        .HasDatabaseName("ix_deployment_logs_deployment_id_id");

                    b.ToTable("deployment_logs", null, t =>
                        {
                            t.HasCheckConstraint("ck_deployment_logs_level", "level IN ('Info', 'Warning', 'Error')");

                            t.HasCheckConstraint("ck_deployment_logs_stage", "stage IN ('Preparing', 'Building', 'Testing', 'Deploying')");
                        });
                });

            modelBuilder.Entity("DevForge.Domain.Builds.Build", b =>
                {
                    b.HasOne("DevForge.Domain.Applications.App", null)
                        .WithMany("Builds")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_builds_applications_application_id");
                });

            modelBuilder.Entity("DevForge.Domain.Deployments.Deployment", b =>
                {
                    b.HasOne("DevForge.Domain.Applications.App", "Application")
                        .WithMany("Deployments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deployments_applications_application_id");

                    b.HasOne("DevForge.Domain.Builds.Build", "Build")
                        .WithMany()
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_deployments_builds_build_id");

                    b.Navigation("Application");

                    b.Navigation("Build");
                });

            modelBuilder.Entity("DevForge.Domain.Deployments.DeploymentLog", b =>
                {
                    b.HasOne("DevForge.Domain.Deployments.Deployment", null)
                        .WithMany("Logs")
                        .HasForeignKey("DeploymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deployment_logs_deployments_deployment_id");
                });

            modelBuilder.Entity("DevForge.Domain.Applications.App", b =>
                {
                    b.Navigation("Builds");

                    b.Navigation("Deployments");
                });

            modelBuilder.Entity("DevForge.Domain.Deployments.Deployment", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
